title: "IN-CORE Manual<br /><span style='color:grey;font-size:smaller;'>4.9.0<span>"
project: "IN-CORE Manual"
author: IN-CORE Community
copyright: "2023"  # Copyright year to be placed in the footer
logo: images/resilience-logo.png
version: "4.9.0"  # Version is not part of JB config, we use it for autobuild of incore-docs
exclude_patterns: [_build, .DS_Store, "**.ipynb_checkpoints"]

repository:
    path_to_book: "content"

html:
  home_page_in_navbar: true # Whether to include your home page in the left Navigation Bar

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled, including those that are enabled by default!
    - html_image
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links

execute:
  execute_notebooks: "off"
