title: "IN-CORE manual"
author: IN-CORE Community
logo: images/resilience-logo.png
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled, including those that are enabled by default!
    - html_image
execute:
  execute_notebooks: "off"