name: Publish JupyterBook to GitHub Pages

on:
  push:
  pull_request:
    types: [ opened, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        sudo apt-get install python3-pip
        pip install ghp-import
        pip install -U jupyter-book

    - name: Build book HTML
      run: |
        jupyter-book build ./manual_jb/content       

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./manual_jb/content/_build/html